DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS shots;
DROP TABLE IF EXISTS goalkeepers;
DROP TABLE IF EXISTS matchs;

CREATE TABLE matchs (
    team_h VARCHAR NOT NULL,
    team_a VARCHAR NOT NULL,
    season VARCHAR NOT NULL,
    goal_h INT NOT NULL,
    goal_a INT NOT NULL,
    competition VARCHAR NOT NULL,
    date_match DATE NOT NULL,
    time_match TIME,
    matchweek INT,
    round VARCHAR,
    manager_h VARCHAR,
    manager_a VARCHAR,
    captain_h VARCHAR,
    captain_a VARCHAR,
    attendance INT,
    venue VARCHAR,
    history_win_h INT,
    history_defeat_h INT,
    history_draw_h INT,
    history_win_a INT,
    history_defeat_a INT,
    history_draw_a INT,
    officials_referee VARCHAR,
    ar1 VARCHAR,
    ar2 VARCHAR,
    fourth VARCHAR,
    var VARCHAR,
    formation_h VARCHAR,
    formation_a VARCHAR,
    xg_a FLOAT,
    xg_h FLOAT,
    penalties_h INT,
    penalties_a INT,
    fouls_h INT,
    fouls_a INT,
    corners_h INT,
    corners_a INT,
    crosses_h INT,
    crosses_a INT,
    touches_h INT,
    touches_a INT,
    tackles_h INT,
    tackles_a INT,
    interceptions_h INT,
    interceptions_a INT,
    aerials_won_h INT,
    aerials_won_a INT,
    clearances_h INT,
    clearances_a INT,
    offsides_h INT,
    offsides_a INT,
    goal_kicks_h INT,
    goal_kicks_a INT,
    throw_ins_h INT,
    throw_ins_a INT,
    long_balls_h INT,
    long_balls_a INT,
    possession_h INT,
    possession_a INT,
    passing_accuracy_success_h INT,
    passing_accuracy_fail_h INT,
    passing_accuracy_success_a INT,
    passing_accuracy_fail_a INT,
    shots_target_success_h INT,
    shots_target_fail_h INT,
    shots_target_success_a INT,
    shots_target_fail_a INT,
    saves_success_h INT,
    saves_fail_h INT,
    saves_success_a INT,
    saves_fail_a INT,
    yellow_card_h INT,
    yellow_card_a INT,
    red_card_h INT,
    red_card_a INT,
    notes VARCHAR,
    PRIMARY KEY (team_h, team_a, date_match)
);

CREATE TABLE players (
    id_player INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    team_h VARCHAR NOT NULL,
    team_a VARCHAR NOT NULL,
    date_match DATE NOT NULL,
    name_player VARCHAR NOT NULL,
    team_player VARCHAR NOT NULL,
    num INT,
    nation VARCHAR,
    pos VARCHAR,
    age_player VARCHAR,
    holder INT,
    min_played INT,
    performance_gls INT,
    performance_ast INT,
    performance_pk INT,
    performance_pkatt INT,
    performance_sh INT,
    performance_sot INT,
    performance_crdy INT,
    performance_crdr INT,
    performance_touches INT,
    performance_tkl INT,
    performance_int INT,
    performance_blocks INT,
    expected_xg FLOAT,
    expected_npxg FLOAT,
    expected_xag FLOAT,
    sca_sca INT,
    sca_gca INT,
    passes_cmp INT,
    passes_att INT,
    passes_cmp_percent FLOAT,
    passes_prgp INT,
    carries_carries INT,
    carries_prgc INT,
    take_ons_att INT,
    take_ons_succ INT,
    total_cmp INT,
    total_att INT,
    total_cmp_percent FLOAT,
    total_totdist INT,
    total_prgdist INT,
    short_cmp INT,
    short_att INT,
    short_cmp_percent FLOAT,
    medium_cmp INT,
    medium_att INT,
    medium_cmp_percent FLOAT,
    long_cmp INT,
    long_att INT,
    long_cmp_percent FLOAT,
    ast INT,
    xag FLOAT,
    xa FLOAT,
    kp INT,
    final_1_3 INT,
    ppa INT,
    crspa INT,
    prgp INT,
    att INT,
    pass_types_live INT,
    pass_types_dead INT,
    pass_types_fk INT,
    pass_types_tb INT,
    pass_types_sw INT,
    pass_types_crs INT,
    pass_types_ti INT,
    pass_types_ck INT,
    corner_kicks_in INT,
    corner_kicks_out INT,
    corner_kicks_str INT,
    outcomes_cmp INT,
    outcomes_off INT,
    outcomes_blocks INT,
    tackles_tkl INT,
    tackles_tklw INT,
    tackles_def_3rd INT,
    tackles_mid_3rd INT,
    tackles_att_3rd INT,
    challenges_tkl INT,
    challenges_att INT,
    challenges_tkl_percent FlOAT,
    challenges_lost INT,
    blocks_blocks INT,
    blocks_sh INT,
    blocks_pass INT,
    interceptions INT,
    tkl_plus_int INT,
    clr INT,
    err INT,
    touches_touches INT,
    touches_def_pen INT,
    touches_def_3rd INT,
    touches_mid_3rd INT,
    touches_att_3rd INT,
    touches_att_pen INT,
    touches_live INT,
    take_ons_succ_percent FLOAT,
    take_ons_tkld INT,
    take_ons_tkld_percent INT,
    carries_totdist INT,
    carries_prgdist INT,
    carries_1_3 INT,
    carries_cpa INT,
    carries_mis INT,
    carries_dis INT,
    receiving_rec INT,
    receiving_prgr INT,
    performance_2crdy INT,
    performance_fls INT,
    performance_fld INT,
    performance_off INT,
    performance_crs INT,
    performance_tklw INT,
    performance_pkwon INT,
    performance_pkcon INT,
    performance_og INT,
    performance_recov INT,
    aerial_duels_won INT,
    aerial_duels_lost INT,
    aerial_duels_won_percent FLOAT,
    FOREIGN KEY (team_h, team_a, date_match) REFERENCES matchs(team_h, team_a, date_match)
);


CREATE TABLE goalkeepers (
    id_goalkeeper INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    team_h VARCHAR NOT NULL,
    team_a VARCHAR NOT NULL,
    date_match DATE NOT NULL,
    name_goalkeeper VARCHAR NOT NULL,
    team_goalkeeper VARCHAR NOT NULL,
    min_played INT,
    shot_stopping_sota INT,
    shot_stopping_ga INT,
    shot_stopping_saves INT,
    shot_stopping_save_percent FLOAT,
    shot_stopping_psxg FLOAT,
    launched_cmp INT,
    launched_att INT,
    launched_cmp_percent FLOAT,
    passes_att_gk INT,
    passes_thr INT,
    passes_launch_percent FLOAT,
    passes_avg_len FLOAT,
    goal_kicks_att INT,
    goal_kicks_launch_percent FLOAT,
    goal_kicks_avg_len FLOAT,
    crosses_opp INT,
    crosses_stp INT,
    crosses_stp_percent FLOAT,
    sweeper_opa INT,
    sweeper_avg_dist FLOAT,
    FOREIGN KEY (team_h, team_a, date_match) REFERENCES matchs(team_h, team_a, date_match)
);


CREATE TABLE events (
    id_event INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    team_h VARCHAR NOT NULL,
    team_a VARCHAR NOT NULL,
    date_match DATE NOT NULL,
    min_event VARCHAR NOT NULL,
    type_event VARCHAR NOT NULL,
    team VARCHAR NOT NULL,
    player VARCHAR,
    score VARCHAR NOT NULL,
    scorer VARCHAR,
    assister VARCHAR,
    incoming VARCHAR,
    outcoming VARCHAR,
    own_goal VARCHAR,
    penalty_saved_by VARCHAR,
    FOREIGN KEY (team_h, team_a, date_match) REFERENCES matchs(team_h, team_a, date_match)
);


CREATE TABLE shots (
    id_shot INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    team_h VARCHAR NOT NULL,
    team_a VARCHAR NOT NULL,
    date_match DATE NOT NULL,
    player VARCHAR NOT NULL,
    minute_shot VARCHAR NOT NULL,
    team VARCHAR NOT NULL,
    xg FLOAT,
    outcome VARCHAR,
    distance FLOAT,
    penalty VARCHAR,
    body_part VARCHAR,
    sca_1_player VARCHAR,
    sca_1_event VARCHAR,
    sca_2_player VARCHAR,
    sca_2_event VARCHAR,
    FOREIGN KEY (team_h, team_a, date_match) REFERENCES matchs(team_h, team_a, date_match)
);